CREATE TABLE SEASONS (
  ID NUMBER NOT NULL,
  TVSHOW_ID_FK NUMBER NOT NULL ,
  SEASON_NUMBER NUMBER NOT NULL ,
  SEASON_RELEASE_DATE DATE,
  SEEN NUMBER(1),
  SEEN_TIME DATE,
  CREATION_TIME DATE NOT NULL
);

COMMENT ON COLUMN SEASONS.ID is 'Technische ID.';
COMMENT ON COLUMN SEASONS.TVSHOW_ID_FK is 'Fremdschluessel auf Serie.';
COMMENT ON COLUMN SEASONS.SEASON_NUMBER IS 'Staffelnummer (startet immer mit 1)';
COMMENT ON COLUMN SEASONS.SEASON_RELEASE_DATE IS 'Erscheinungsdatum der Staffel.';
COMMENT ON COLUMN SEASONS.SEEN IS 'Boolean value: 1=gesehen, 0=noch nicht gesehen.';
COMMENT ON COLUMN SEASONS.SEEN_TIME IS 'Datum, an dem die letzte Folge der Staffel angesehen wurde.';

ALTER TABLE SEASONS ADD CONSTRAINT PK_SEASONS PRIMARY KEY (ID);
ALTER TABLE SEASONS ADD CONSTRAINT FK_TVSHOWS FOREIGN KEY (TVSHOW_ID_FK) REFERENCES TVSHOWS (ID);
ALTER TABLE SEASONS ADD CONSTRAINT CHECK_SEEN_01 CHECK (SEEN in (0,1));
